Developer
maya88en/Mint.com pull request #1
Opened 2019-06-20 16:27 UTC by maya88en

2019-06-20 17:38 UTC, bellom requested changes
Hi @maya88en @Anna-Myzukina,
Great work guys....just few things left.
Here is the checklist for your project.
- To consider the project 'complete' it must satisfy the following points:
## General
- [x] The project has a descriptive README.md 
## Intuit logo
* [x] It shows the Intuit logo above the form
* [x] The intuit logo is an embedded image that is horizontally centered
## Intuit products
* [ ] There is a dedicated container for displaying intuit's products (mint, quickbox, turbotax)
* [ ] The products are displayed in a single row
* [ ] The products row is under the Intuit logo and above the form
* [ ] It shows the Mint logo and text (logo on the left, text on the right)
* [ ] It shows the Quickbooks logo and text (logo on the left, text on the right)
* [ ] It shows the Turbotax logo and text (logo on the left, text on the right)
## kindly check out the mint original sign up page to see the logos....
After fixing the _**unchecked**_ issues please send another request to re-review this project.

2019-06-20 17:38 UTC, bellom commented on index.html
> +    <div class="footer_container">
footer tag should not be inside a div tag, kindly correct this.....click [here](https://www.themelocation.com/best-html5-practices/) to check the right way to do it.

2019-06-22 00:37 UTC, Torres-ssf commented
Hi there @maya88en @Anna-Myzukina...
Your project looks very good 👏
I noticed that you added the 3 missing logos to the HTML code but it seems that the image files are missing from your project. Before I give your project a 👍, please kindly add the 3 image files to your project.

2019-06-22 00:40 UTC, Torres-ssf requested changes

2019-06-22 00:40 UTC, Torres-ssf commented on index.html
> +                    <input id="email" class="form_input" name="email" type="text" value="" required="required" pattern="[A-Za-z0-9]" maxlength="100" title="You'll use this as your user ID">
You can use the value `email` for the attribute `type`. It will make your code even better.

2019-06-24 11:02 UTC, Torres-ssf commented
### Congratulation team 👍
You can submit to master now. Don't forget to submit the form.

2019-06-24 13:53 UTC, merged